name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@master
      - name: Run on Alpine Linux
        run: sh test/run.sh docker debian
      - name: Run on Debian
        run: sh test/run.sh docker alpine